# CMake generated Testfile for 
# Source directory: /home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing
# Build directory: /home/vuola/matres/UH_NumericalMethods/eigen5/blas/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(sblat1 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "sblat1" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/sblat1.dat")
set_tests_properties(sblat1 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;32;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(sblat2 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "sblat2" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/sblat2.dat")
set_tests_properties(sblat2 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;33;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(sblat3 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "sblat3" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/sblat3.dat")
set_tests_properties(sblat3 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;34;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(dblat1 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "dblat1" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/dblat1.dat")
set_tests_properties(dblat1 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;36;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(dblat2 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "dblat2" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/dblat2.dat")
set_tests_properties(dblat2 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;37;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(dblat3 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "dblat3" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/dblat3.dat")
set_tests_properties(dblat3 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;38;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(cblat1 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "cblat1" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/cblat1.dat")
set_tests_properties(cblat1 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;40;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(cblat2 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "cblat2" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/cblat2.dat")
set_tests_properties(cblat2 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;41;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(cblat3 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "cblat3" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/cblat3.dat")
set_tests_properties(cblat3 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;42;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(zblat1 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "zblat1" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/zblat1.dat")
set_tests_properties(zblat1 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;44;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(zblat2 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "zblat2" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/zblat2.dat")
set_tests_properties(zblat2 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;45;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
add_test(zblat3 "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/runblastest.sh" "zblat3" "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/zblat3.dat")
set_tests_properties(zblat3 PROPERTIES  _BACKTRACE_TRIPLES "/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;27;add_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;46;ei_add_blas_test;/home/vuola/matres/UH_NumericalMethods/eigen-5.0.1/blas/testing/CMakeLists.txt;0;")
